//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandaWebUtility.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountEmailSMTP
    {
        public System.Guid EmailSettingId { get; set; }
        public byte[] RowVersion { get; set; }
        public string FromEmailAddress { get; set; }
        public string Host { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int Port { get; set; }
        public string UserModified { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool UseSSL { get; set; }
    }
}
