//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandaWebUtility.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINLOCAT
    {
        public System.Guid ROWID { get; set; }
        public string BINLABEL { get; set; }
        public string PRODUCT { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<decimal> PACKSIZE { get; set; }
        public Nullable<decimal> UNALLOC { get; set; }
        public string USER_ID { get; set; }
        public string CLIENT { get; set; }
        public Nullable<decimal> COUNTED { get; set; }
        public string EXTENDED { get; set; }
        public string PO_NUM { get; set; }
        public string RECV_SLIP { get; set; }
        public string RETURN_BIN { get; set; }
        public string WAREHOUSE { get; set; }
        public string COMMENT_IN { get; set; }
        public string RESERVED { get; set; }
        public Nullable<System.DateTime> DATECREATE { get; set; }
        public string TOWER { get; set; }
        public string MODIFIED { get; set; }
        public string RECV_PONUM { get; set; }
        public string LINE_NUM { get; set; }
        public string CLIENTNAME { get; set; }
        public string TENANTID { get; set; }
        public string DATE_TIME { get; set; }
        public string CNT_USER_ID { get; set; }
        public string LICENSE_PLATE { get; set; }
        public string TRANSFER { get; set; }
        public string TIMECREATE { get; set; }
        public Nullable<decimal> PO_LINE_UNIT_COST { get; set; }
        public Nullable<decimal> ADDED_UNIT_COST { get; set; }
        public Nullable<decimal> TOTAL_UNIT_COST { get; set; }
        public string BINTYPE { get; set; }
        public string FROM_BIN { get; set; }
        public Nullable<int> INNERPACK { get; set; }
        public string LOCATION { get; set; }
        public Nullable<int> MAX_PACK { get; set; }
        public Nullable<int> MIN_PACK { get; set; }
        public Nullable<int> PUSHBACK { get; set; }
        public string ZONE { get; set; }
        public string IS_BONDED { get; set; }
        public string EXTRA1 { get; set; }
        public string EXTRA2 { get; set; }
        public string VEND_NUM { get; set; }
        public Nullable<System.DateTime> DATE_RECVD { get; set; }
        public Nullable<System.DateTime> DATE_SHIPPED { get; set; }
        public string PACKSLIP { get; set; }
        public string ORDER_SEQ { get; set; }
        public string CUST_NUM { get; set; }
        public Nullable<decimal> SO_LINE_UNIT_PRICE { get; set; }
        public Nullable<decimal> GROSS_PROFIT { get; set; }
        public string PROD_CLASS { get; set; }
        public string SALESMAN { get; set; }
        public string BUYER { get; set; }
        public string DOCUMENT_REF { get; set; }
        public decimal Unallocated { get; set; }
        public string ABC { get; set; }
    }
}
