//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandaWebUtility.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logging
    {
        public System.Guid ROWID { get; set; }
        public System.DateTime DateTimeStamp { get; set; }
        public string User { get; set; }
        public string Action { get; set; }
        public string Message { get; set; }
        public string FromValue { get; set; }
        public string ToValue { get; set; }
    }
}
