//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandaWebUtility.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASSWORD
    {
        public System.Guid ROWID { get; set; }
        public string ISADMIN { get; set; }
        public string ID { get; set; }
        public string NAME { get; set; }
        public string PASSWORD1 { get; set; }
        public Nullable<short> PRIVILEGE { get; set; }
        public string CLIENTNAME { get; set; }
        public string TENANTID { get; set; }
        public string SECURITY { get; set; }
        public Nullable<short> PRNTR_PICK { get; set; }
        public Nullable<short> PRNTR_RECV { get; set; }
        public Nullable<short> PRNTR_SHIP { get; set; }
        public Nullable<short> PRNTR_PACK { get; set; }
        public string USER_LANG { get; set; }
        public string CUST_NUM { get; set; }
        public Nullable<long> RFTERMID { get; set; }
        public string COMPUTER { get; set; }
        public string LOCATION { get; set; }
        public Nullable<short> PRNTR_BIN { get; set; }
        public Nullable<short> PRNTR_PROD { get; set; }
    }
}
