//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandaWebUtility.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODMSTR
    {
        public System.Guid ROWID { get; set; }
        public string PRODUCT { get; set; }
        public string ITEMTYPE { get; set; }
        public string DESCRIPT { get; set; }
        public string UNITMEASUR { get; set; }
        public string IS_SERIAL { get; set; }
        public string BINLABEL { get; set; }
        public string DYNAMICBIN { get; set; }
        public string AGGRE_BIN { get; set; }
        public string BULKSLOT { get; set; }
        public Nullable<int> CARTON_DEF { get; set; }
        public string LOC_SIZE { get; set; }
        public string ZONE_CODE { get; set; }
        public Nullable<long> BOOK_COUNT { get; set; }
        public Nullable<decimal> REPLEN_QTY { get; set; }
        public Nullable<int> Q_ALLOCATE { get; set; }
        public Nullable<int> TIE_COUNT { get; set; }
        public Nullable<int> HIGHCOUNT { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<decimal> CUBAGE { get; set; }
        public string FLOOR_STK { get; set; }
        public Nullable<decimal> SELL_PRICE { get; set; }
        public Nullable<decimal> COST_PRICE { get; set; }
        public string UPC { get; set; }
        public string EXTENDED { get; set; }
        public string SUBSTITUTE { get; set; }
        public Nullable<decimal> AVG_PICKS { get; set; }
        public Nullable<decimal> AVG_UNITS { get; set; }
        public Nullable<decimal> AVG_CUBE { get; set; }
        public string PROD_CLASS { get; set; }
        public string RECV_ATTR { get; set; }
        public string PICK_ATTR { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUT10 { get; set; }
        public string ASSEMBLY { get; set; }
        public Nullable<int> FIFTY_RULE { get; set; }
        public Nullable<short> LEAD_TIME { get; set; }
        public string ORDERGROUPS { get; set; }
        public string REFORECAST { get; set; }
        public Nullable<decimal> VEND_PACKSIZE { get; set; }
        public Nullable<System.DateTime> DATECREATE { get; set; }
        public Nullable<System.DateTime> DATE_MODFY { get; set; }
        public Nullable<decimal> SIZE1 { get; set; }
        public Nullable<decimal> SIZE2 { get; set; }
        public Nullable<decimal> SIZE3 { get; set; }
        public Nullable<decimal> SIZE4 { get; set; }
        public Nullable<decimal> SIZE5 { get; set; }
        public Nullable<decimal> FORECAST { get; set; }
        public string DFLTRANDOM { get; set; }
        public string HANDLECODE { get; set; }
        public string SIZECODE { get; set; }
        public string REACHCODE { get; set; }
        public string EXPIRYDATE { get; set; }
        public Nullable<int> MIN_PACK1 { get; set; }
        public Nullable<int> MIN_PACK2 { get; set; }
        public Nullable<int> MIN_PACK3 { get; set; }
        public Nullable<int> MIN_PACK4 { get; set; }
        public Nullable<int> MIN_PACK5 { get; set; }
        public Nullable<int> MIN_UNITS { get; set; }
        public Nullable<int> MIN_INNER { get; set; }
        public Nullable<int> MIN_CARTON { get; set; }
        public Nullable<decimal> CONV_QTY { get; set; }
        public Nullable<short> STOCK_ITEM { get; set; }
        public Nullable<int> M_T_D { get; set; }
        public string VEND_NUM { get; set; }
        public decimal ON_HAND { get; set; }
        public decimal ON_SALES { get; set; }
        public decimal ON_PURCH { get; set; }
        public decimal NET_STOCK { get; set; }
        public Nullable<int> FREE_SAMPL { get; set; }
        public string EDP_NUM { get; set; }
        public string FREIGHT_CL { get; set; }
        public string TARIFF_CL { get; set; }
        public string C_ORIGIN { get; set; }
        public string HAZMAT { get; set; }
        public string CLIENTNAME { get; set; }
        public string TENANTID { get; set; }
        public string VEND_PROD { get; set; }
        public Nullable<int> TRIG_PNT { get; set; }
        public Nullable<short> TRIG_VAL { get; set; }
        public string ORD_GROUP { get; set; }
        public Nullable<int> REORDER { get; set; }
        public string BUYER { get; set; }
        public Nullable<int> GRP_LIMIT1 { get; set; }
        public Nullable<int> GRP_LIMIT2 { get; set; }
        public Nullable<int> GRP_LIMIT3 { get; set; }
        public Nullable<int> GRP_LIMIT4 { get; set; }
        public Nullable<int> GRP_LIMIT5 { get; set; }
        public Nullable<int> GRP_LIMIT6 { get; set; }
        public Nullable<int> GRP_LIMIT7 { get; set; }
        public Nullable<int> GRP_LIMIT8 { get; set; }
        public Nullable<int> GRP_LIMIT9 { get; set; }
        public string COMMODITY { get; set; }
        public string STACKABLE { get; set; }
        public string RECYCLABLE { get; set; }
        public string EXPLODEKIT { get; set; }
        public Nullable<decimal> TOLERANCE { get; set; }
        public Nullable<int> SHELF_LIFE { get; set; }
        public Nullable<int> MAX_PACK1 { get; set; }
        public Nullable<int> MAX_PACK2 { get; set; }
        public Nullable<int> MAX_PACK3 { get; set; }
        public Nullable<int> MAX_PACK4 { get; set; }
        public Nullable<int> MAX_PACK5 { get; set; }
        public string CURRENCY_ID { get; set; }
        public Nullable<long> FORECAST_6 { get; set; }
        public string FORECAST_TYPE { get; set; }
        public Nullable<short> F_TYPE { get; set; }
        public Nullable<int> INNERPACK1 { get; set; }
        public Nullable<int> INNERPACK2 { get; set; }
        public Nullable<int> INNERPACK3 { get; set; }
        public Nullable<int> INNERPACK4 { get; set; }
        public Nullable<int> INNERPACK5 { get; set; }
        public Nullable<decimal> INVENTORY_QTY { get; set; }
        public Nullable<int> RESERVE_MIN { get; set; }
        public Nullable<int> SKU_ID { get; set; }
        public string STATUS { get; set; }
        public Nullable<long> STOCKOUT { get; set; }
        public string BOX_SIZE { get; set; }
        public string PROD_UDF1 { get; set; }
        public string PROD_UDF2 { get; set; }
        public string PROD_UDF3 { get; set; }
        public string PROD_UDF4 { get; set; }
        public string PROD_UDF5 { get; set; }
        public string PACK_CLASS { get; set; }
        public Nullable<System.DateTime> LASTCOUNT { get; set; }
        public Nullable<int> OVERDUE { get; set; }
        public string STOCK_STATUS { get; set; }
        public string CLIENTNO { get; set; }
        public Nullable<decimal> MIN_QTY { get; set; }
        public Nullable<decimal> MAX_QTY { get; set; }
        public string ITEM_OWNER { get; set; }
        public Nullable<int> EXPIRY_DAYS { get; set; }
        public string STICKY_BIN { get; set; }
        public Nullable<System.DateTime> MODIFIED_TIME { get; set; }
        public string UPDATE_FLAG { get; set; }
        public Nullable<long> INV_BILL_NET { get; set; }
        public Nullable<System.DateTime> INV_BILL_DATE { get; set; }
        public Nullable<short> PRECISION { get; set; }
        public Nullable<short> PRECISION_PACKS { get; set; }
        public string RECV_OVER_PERCENT { get; set; }
        public string DOCUMENT_REF { get; set; }
        public string OuterPack { get; set; }
        public string InnerPack { get; set; }
        public string ISBN { get; set; }
        public string EAN { get; set; }
        public string UPCCaseCode { get; set; }
        public string NatlDrugCode { get; set; }
        public string GTIN { get; set; }
        public bool SmartCartValidateDimensions { get; set; }
        public bool IsBase { get; set; }
        public string EXTENDED2 { get; set; }
    }
}
